#!/usr/bin/python3 -u
import json
import vdstatus
import time


print('{"version":1}')
print('[')
while True:
    output = vdstatus.run_plugins()
    print(json.dumps(output) + ',')
    time.sleep(1)
