#!/usr/bin/python3 -u
from sys import argv
import argparse
import vdstatus


def parse_arguments(arguments=argv[1:]):
    desc = ('A simple i3status replacement, '
            'and more. Warning: WIP, may be broken.')
    p = argparse.ArgumentParser(description=desc)
    p.add_argument('-c', '--config', help='configuration file')

    return p.parse_args(arguments)


if __name__ == '__main__':
    args = parse_arguments()
    if args.config is not None:
        vdstatus.run_plugins(args.config)
    else:
        vdstatus.run_plugins()
